image: "node:10.16"

cache:
  paths:
    - node_modules

pages:
  stage: "deploy"
  only:
    - master
  script:
    - npm i
    - git clone https://gitlab.com/pjsekai/sprites.git src/sprites
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
